from global_settings import PROJECT_PATH

IMAGE_EXTENSION = "png"
IMAGE_FORMAT = "PNG"
IMAGE_MINIMUM_ASPECT_RATIO = 0.3

FILE_UPLOAD_PATH = PROJECT_PATH+"/static/upload"
FILE_UPLOAD_URL = "/static/upload"
FILE_TEMPORARY_UPLOAD_PATH = "/tmp"
FILE_MAX_SIZE = 1024*1024*10.

PROFILE_IMAGE_DIMENSIONS = (200,200)
COVER_IMAGE_WIDTH = 200
PROFILE_IMAGE_SMALL_DIMENSIONS = (128,128)
PROFILE_IMAGE_THUMBNAIL_DIMENSIONS = (40,40)
PROFILE_IMAGE_PLACEHOLDER_ID = 1
ORGANIZATION_IMAGE_PLACEHOLDER_ID = 1
IMAGE_MAXIMUM_DIMENSIONS = (1200,1200)

CONFIRM_SIGNUP_BY_ADMIN = False

DEFAULT_URL_AFTER_LOGIN = 'websites.views.dashboard'
