from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from profiles.views import *

urlpatterns = patterns('',
    url(r'^logout/?$', logout),
    url(r'^login/?$', login),
    url(r'^logout_and_goto(?P<url>.*)$', logout_and_goto),
    url(r'^login/as/(?P<email>[^\/]*)$', login),
    url(r'^login/and/goto(?P<next_url>.*)$', login),
    url(r'^login/as/(?P<email>[^\/]+)/and/goto(?P<next_url>.*)$', login),
    url(r'^login$', login),
    url(r'^login_or_signup/?$', login_or_signup),
    url(r'^login_or_signup/and/goto(?P<next_url>.*)$', login_or_signup),
    url(r'^send_activation_key/(\d+)$', send_activation_key),
    url(r'^delete_activation_key/(\d+)$', delete_activation_key),
    url(r'^remove_profile_image$', remove_profile_image),
    url(r'^change_profile_image$', change_profile_image),
    url(r'^change_profile_image_clipping$', change_profile_image_clipping),
    url(r'^login_with_access_key/?$',login_with_access_key),
    url(r'^login_with_access_key/(?P<access_key>[^\/]*)$',login_with_access_key),
    url(r'^login_with_access_key/next(?P<next_url>.*)$',login_with_access_key),
    url(r'^login_with_access_key/(?P<access_key>[^\/]*)/next(?P<next_url>.*)$',login_with_access_key),
    url(r'^delete_account/(?P<account_deletion_key>.*)$',delete_account),
    url(r'^request_account_deletion_key',request_account_deletion_key),
    url(r'^change_email$',change_email),
    url(r'^change_password$',change_password),
    url(r'^activate_account/(?P<account_activation_key>[\w\d]+)$',activate_account),
    url(r'^change_email/(?P<email_change_key>[\w\d]+)$',change_email),
    url(r'^reset_password/(?P<password_reset_key>[\w\d]+)$',reset_password),
    url(r'^resend_account_activation_key/?(?P<email>.*?)$',resend_account_activation_key),
    url(r'^resend_account_activation_key$',resend_account_activation_key),
    url(r'^request_email_change_key$',request_email_change_key),
    url(r'^request_access_key$',request_access_key),
    url(r'^request_access_key_for/?(?P<email>.*?)$',request_access_key),
    url(r'^signup$',signup),
    url(r'^signup/and/goto(?P<next_url>.*)$',signup),
    url(r'^profile/?$',profile),
    url(r'^profile/(?P<user_id>\d+)$',profile),
    url(r'^settings$',profile_settings),
    url(r'^change_chamaeleon_username$',change_chamaeleon_username),
    url(r'^change_name$',change_name),
    url(r'^change_username$',change_username),
    url(r'^signup_next_steps$', 'django.views.generic.simple.direct_to_template', {'template': 'profiles/signup_next_steps.html'},name='profiles_signup_next_steps'),
    url(r'^account_deletion_key_sent$', 'django.views.generic.simple.direct_to_template', {'template': 'profiles/account_deletion_key_sent.html'},name='profiles_account_deletion_key_sent')
    )
